deb: &deb
  desc: deb的安装方式
  compatible:
    - Debian
  installation_page:
  comment:
  args:
  run:
    - wget https://obsidian.md/download -O /tmp/obsidian.html
    - url=$(cat /tmp/obsidian.html |grep -Eo "https.*deb")
    - wget $url -O /tmp/obsidian.deb
    - apt install -y /tmp/obsidian.deb
  role1:
    -
default:
  *deb