viewer: &viewer
  desc: viewer
  compatible:
    - Debian
  installation_page:
  comment:
  args:
  run:
    - wget https://www.realvnc.com/en/connect/download/viewer/ -O /tmp/realvnc_viewer.html
    - url=$(cat /tmp/realvnc_viewer.html |grep -Eo "http.*deb"|grep x64 -m 1)
    - wget $url -O /tmp/realvnc_viewer.deb
  role1:
    - apt install -y /tmp/realvnc_viewer.deb
default:
  *viewer