docker: &docker
  desc: 用docker的方式安装spark版本的微信，目前功能最全的版本了
  compatible:
    - Debian
  run: &run
    - mkdir -p ${software_dir}/wechat
    - cd ${software_dir}/wechat
    - echo "Downloading WeChat for Linux..." > docker-compose.yml
  role1:
    - *run
default:
  *docker