dingtalk: &dingtalk
  compatible:
    - Debian
  default_run: 
    - wget https://g.alicdn.com/dingding/h5-home-download/0.2.6/js/index.js -O /tmp/dingtalk.js
    - json=$(grep -Eo "\[\{name.*deb\"\}\]" /tmp/dingtalk.js)
    # 根据架构选择下载链接
    - url=$(echo $json|grep -Eo "http.*amd64.deb")
    - wget $url -O /tmp/dingtalk.deb
    - apt install /tmp/dingtalk.deb -y
  role1:
    - *run
default:
  *dingtalk