google-chrome: &google-chrome
  compatible:
    - Debian
  run:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb
default:
  *google-chrome