x86: &x86
  desc: x86
  compatible:
    - Debian
  installation_page:
  comment:
  args:
  run: 
    - wget https://telegram.org/dl/desktop/linux -O /tmp/telegram.deb
  role1:
    - apt install -y /tmp/telegram.deb
default:
  *x86