latest: &latest
  compatible:
    - Debian
  run: &run
    - wget https://builds.parsec.app/package/parsec-linux.deb -O /tmp/parsec-linux.deb
    - apt install /tmp/parsec-linux.deb -y
  role1:
    - *run
default:
  *latest