latest: &latest
  compatible:
    - Debian
  installation_page:
  comment:
  args:
  run: 
    - wget https://builds.parsec.app/package/parsec-linux.deb -O /tmp/parsec-linux.deb
    - apt install /tmp/parsec-linux.deb -y
  role1:
    -
default:
  *latest