gui: &gui
  desc: 默认界面版
  compatible:
    - Debian
  default_run:
  role1:
    - apt install -y transmission-gtk
daemon: &daemon
  desc: 仅服务端
  compatible:
    - Debian
  default_run:
  role1:
    - apt install -y transmission-daemon
default:
  *gui