auto_command: &auto_command
  desc: ZeroTier
  compatible:
    - Debian
  installation_page:
  comment:
  args:
  run: 
    - curl -s https://install.zerotier.com | sudo bash
  role1:
    -
default:
  *auto_command