community: &community
  desc: pycharm community版本
  compatible:
    - Debian
  default_run:
    - wget "https://download.jetbrains.com/python/pycharm-community-2023.3.2.tar.gz" -O /tmp/pycharm.tar.gz
  role1:
    - tar xvf /tmp/pycharm.tar.gz -C ${software_dir}/
    - |-
      echo "[Desktop Entry]
      Type=Application
      Name=PyCharm
      Comment=The Python IDE for Professional Developers
      Exec=${software_dir}/pycharm/bin/pycharm.sh
      Icon=${software_dir}/pycharm/bin/pycharm.png
      Terminal=false
      Categories=Development;IDE;"
      > /usr/share/applications/pycharm.desktop
default:
  *community